#!/usr/bin/env node
// Install, update or check the hivemind skill for Claude Code or Codex, on any OS (Node 22.5+, which context-mode needs).
// install.sh and install.ps1 are thin wrappers around this file.
//
//   node install.js                   link skills/{hivemind,hivemind-review} into ~/.claude/skills
//                                     (every repo; `git pull` here updates them), copy agents/*.md
//                                     to ~/.claude/agents, record this checkout in ~/.claude/hivemind.json,
//                                     install the required context-mode plugin through the claude CLI
//   node install.js --project         also set up the current repo: teams/<profile>/ with skills
//                                     linked per skills.txt, the lead's hooks in
//                                     .claude/settings.local.json (HIVEMIND=0 claude skips them);
//                                     removes project copies of the skill and unmodified agents
//   node install.js --project --install   also `npx skills add` any skill not on this machine
//   node install.js --project --confine   also remove the global ~/.claude/skills/<name> link
//                                         for every linked skill, so the lead never sees it
//   node install.js --update          git pull --ff-only this checkout, reinstall, and refresh the
//                                     current repo too if it is a hivemind project
//   node install.js --auto-update     let the SessionStart hook pull this checkout (off by default);
//   node install.js --no-auto-update  both run the global install and persist the choice
//   node install.js --doctor [--fix]  check the setup; --fix applies the safe local fixes
//   node install.js --tour-done       record the tour as taken (the lead runs it when the tour ends
//                                     or is skipped); the session start stops offering it until
//                                     a new feature lands
//   --harness codex                   any of the above for OpenAI Codex CLI instead (or HIVE_HARNESS=codex;
//                                     default claude): skills linked into ~/.agents/skills, agents as
//                                     TOML in $CODEX_HOME/agents, the lead's hooks in .codex/hooks.json
//                                     and .codex/rules/hivemind.rules, ../<repo>-hive writable in
//                                     .codex/config.toml; --update reinstalls every
//                                     harness recorded in ~/.claude/hivemind.json
"use strict";
const fs = require("fs");
const path = require("path");
const os = require("os");
const crypto = require("crypto");
const { spawnSync } = require("child_process");
const L = require("./teams/link-skills.js");
const { WIN, lstat, real, isDir, isFile, samePath, removeLink, linkDir } = L;

const HERE = __dirname;
const HOME = os.homedir();
const CLAUDE = path.join(HOME, ".claude");
const SKILLS = ["hivemind", "hivemind-review"];
const LINK_SCRIPTS = ["link-skills.js", "link-skills.sh", "link-skills.ps1"];
const EXCLUDE = [".claude/settings.local.json", ".claude/hooks/hive-*.js", ".claude/hooks/worktree-settings.local.json", ".claude/hive-owned"];
const TEAMS_ENV = "CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS";
const CTX_PLUGIN = "context-mode@context-mode";
const CTX_MARKET = "mksglu/context-mode";
const NODE_MIN = "22.5.0";
const HARNESSES = ["claude", "codex"];
const AGENTS_SKILLS = path.join(HOME, ".agents", "skills"); // Codex reads skills here and in <repo>/.agents/skills
const CODEX_EXCLUDE = [".codex/hooks.json", ".codex/hooks/hive-*.js", ".codex/rules/hivemind.rules", ".codex/hive-owned"];
// the commit-msg gate runs from here on every CLI: committed with teams/, refreshed by --project
const COMMIT_MSG = "teams/templates/hooks/commit-msg.js";
const CODEX_CTX = "codex mcp add context-mode --env CONTEXT_MODE_PLATFORM=codex -- npx -y context-mode";
const GENERATED = "# generated by hivemind";
// sha256 (LF line endings) of templates/hooks/settings.local.json as shipped before its rename
const OLD_WORKER_SETTINGS = "365bfd02b83f795a76f0656aeb238f7295c0194dad2babce80ef37bba5692542";

let quiet = false;
let HARNESS = "claude"; // --harness, else HIVE_HARNESS; set in main
const codex = () => HARNESS === "codex";
// the Codex adapter reads CODEX_HOME when loaded: only on the codex path
let cxAd = null;
const cx = () => cxAd || (cxAd = require(path.join(HERE, "templates", "hooks", "hive-harness-codex.js")));
const log = (s = "") => { if (!quiet) console.log(s); };
const warn = (s) => console.error(s);
const die = (s, code = 1) => { warn(s); process.exit(code); };

// helpers

function git(args, cwd) {
  const r = spawnSync("git", args, { cwd, encoding: "utf8", stdio: ["inherit", "pipe", "pipe"] });
  return { ok: r.status === 0, out: (r.stdout || "").trim(), err: (r.stderr || "").trim() };
}
function has(cmd, args = ["--version"]) {
  const r = spawnSync(cmd, args, { encoding: "utf8", shell: WIN, timeout: 20000 });
  return r.status === 0 ? (r.stdout || "").trim() : null;
}
const norm = (s) => s.replace(/\r\n/g, "\n");
const readText = (p) => { try { return fs.readFileSync(p, "utf8"); } catch { return null; } };
const inside = (child, parent) => { const r = path.relative(parent, child); return r === "" || (!r.startsWith("..") && !path.isAbsolute(r)); };

// {} when missing or empty, null when not a JSON object
function readJson(file) {
  const t = readText(file);
  if (t === null || !t.trim()) return {};
  try {
    const v = JSON.parse(t.replace(/^﻿/, ""));
    return v && typeof v === "object" && !Array.isArray(v) ? v : null;
  } catch { return null; }
}
function writeJson(file, v) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, JSON.stringify(v, null, 2) + "\n");
}

function frontmatterName(dir) {
  const t = readText(path.join(dir, "SKILL.md"));
  const fm = t && /^---\r?\n([\s\S]*?)\r?\n---/.exec(t);
  const m = fm && /^name:\s*["']?([^"'\r\n]+?)["']?\s*$/m.exec(fm[1]);
  return m ? m[1] : null;
}

// copy unless identical; a link at dest is replaced, never written through
function copyFile(src, dest) {
  const st = lstat(dest);
  if (st && !st.isSymbolicLink() && fs.readFileSync(src).equals(fs.readFileSync(dest))) return;
  if (st && st.isSymbolicLink()) removeLink(dest);
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  fs.copyFileSync(src, dest);
}
function copyTree(src, dest) {
  for (const e of fs.readdirSync(src, { withFileTypes: true })) {
    const s = path.join(src, e.name), d = path.join(dest, e.name);
    if (e.isDirectory()) copyTree(s, d); else copyFile(s, d);
  }
}

const shippedAgents = () => fs.readdirSync(path.join(HERE, "agents")).filter((f) => f.endsWith(".md")).sort();
const isHiveProject = (dir, h = "claude") => isDir(path.join(dir, "teams")) && isFile(path.join(dir, `.${h}`, "hooks", "hive-autostart.js"));

function envCommand() {
  if (WIN) return `[Environment]::SetEnvironmentVariable("${TEAMS_ENV}", "1", "User")`;
  const sh = path.basename(process.env.SHELL || "");
  if (sh === "fish") return `set -Ux ${TEAMS_ENV} 1`;
  return `echo 'export ${TEAMS_ENV}=1' >> ~/.${sh === "zsh" ? "zshrc" : "bashrc"}`;
}
function teamsEnvOn() {
  const s = readJson(path.join(CLAUDE, "settings.json"));
  return process.env[TEAMS_ENV] === "1" || String(s && s.env && s.env[TEAMS_ENV]) === "1";
}

// global install

function linkSkills(dir = path.join(CLAUDE, "skills")) {
  let ok = true;
  fs.mkdirSync(dir, { recursive: true });
  for (const s of SKILLS) {
    const target = real(path.join(HERE, "skills", s));
    const link = path.join(dir, s);
    const st = lstat(link);
    if (st && !st.isSymbolicLink()) {
      // an old installer's copy is replaced; anything else is someone else's
      if (!st.isDirectory() || frontmatterName(link) !== s || inside(HERE, link)) {
        warn(`error: ${link} is not an old copy of the ${s} skill; move it away and re-run`);
        ok = false;
        continue;
      }
      fs.rmSync(link, { recursive: true, force: true });
      log(`removed  ${link} (old copy, replaced by a link)`);
    }
    linkDir(target, link);
  }
  if (ok) log(`skills   -> ${path.join(dir, "{hivemind,hivemind-review}")} linked to ${path.join(real(HERE), "skills")}`);
  return ok;
}

function copyAgents() {
  const dir = path.join(CLAUDE, "agents");
  const files = shippedAgents();
  for (const f of files) copyFile(path.join(HERE, "agents", f), path.join(dir, f));
  // only what ships is overwritten; other agents there survive
  log(`agents   -> ${dir} (${files.length} shipped, others untouched)`);
}

function setAttribution() {
  const file = path.join(CLAUDE, "settings.json");
  const s = readJson(file);
  if (!s) {
    warn(`warning: ${file} is not valid JSON; left alone. Add by hand:`);
    warn('  "attribution": { "commit": "", "pr": "", "sessionUrl": false }');
    return false;
  }
  const want = { ...(s.attribution || {}), commit: "", pr: "", sessionUrl: false };
  if (JSON.stringify(s.attribution) !== JSON.stringify(want)) { s.attribution = want; writeJson(file, s); }
  log("settings -> attribution disabled");
  return true;
}

// ~/.claude/hivemind.json: { home, autoUpdate, ...keys the hooks own }
const CONFIG = path.join(CLAUDE, "hivemind.json");
function readConfig() {
  const c = readJson(CONFIG);
  if (!c) warn(`warning: ${CONFIG} was not valid JSON; rewritten`);
  return c || {};
}

function writeConfig({ autoUpdate } = {}) {
  const c = readConfig();
  const next = { ...c, home: real(HERE), autoUpdate: autoUpdate ?? (typeof c.autoUpdate === "boolean" ? c.autoUpdate : false) };
  if (!lstat(CONFIG)) next.toured = ""; // first install: the first-time tour; a missing key means an install from before the tour
  // harnesses: every CLI installed here, for --update; absent means claude only
  if (HARNESS !== "claude" || Array.isArray(c.harnesses)) {
    const had = Array.isArray(c.harnesses) ? c.harnesses : c.home ? ["claude"] : [];
    next.harnesses = [...new Set([...had, HARNESS])].filter((h) => HARNESSES.includes(h)).sort();
  }
  delete next.laya; delete next.layaOffered; // keys of a removed option
  if (JSON.stringify(next) !== JSON.stringify(c)) writeJson(CONFIG, next);
  log(`config   -> ${CONFIG} (autoUpdate ${next.autoUpdate})`);
}

function globalInstall(config) {
  const ok = linkSkills();
  copyAgents();
  writeConfig(config);
  installContextMode(); // required, but a missing claude CLI is not fatal: --doctor keeps failing until it is there
  return setAttribution() && ok;
}

// Codex: shipped agents as TOML roles in $CODEX_HOME/agents. A file there without the generated
// header is the user's own and never overwritten.
const codexAgents = () => shippedAgents().map((f) => cx().agentFile(f, fs.readFileSync(path.join(HERE, "agents", f), "utf8"))).filter(Boolean);
function codexAgentState() {
  const dir = cx().agentsDir, stale = [], kept = [];
  for (const a of codexAgents()) {
    const t = readText(path.join(dir, a.name));
    if (t !== null && norm(t) === a.text) continue;
    if (t !== null && !norm(t).startsWith(GENERATED)) kept.push(path.join(dir, a.name)); else stale.push(a);
  }
  return { dir, stale, kept };
}
function copyCodexAgents() {
  const { dir, stale, kept } = codexAgentState();
  for (const a of stale) {
    const p = path.join(dir, a.name);
    if (lstat(p) && lstat(p).isSymbolicLink()) removeLink(p);
    fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(p, a.text);
  }
  for (const p of kept) log(`local override kept: ${p} (not generated by hivemind; delete it to use the shipped one)`);
  log(`agents   -> ${dir} (${codexAgents().length} shipped as TOML, others untouched)`);
}

function codexGlobalInstall(config) {
  const ok = linkSkills(AGENTS_SKILLS);
  copyCodexAgents();
  writeConfig(config);
  return ok;
}

// [projects."<root>"] trust_level = "trusted" in $CODEX_HOME/config.toml, written when the human trusts it
function codexTrusted(root) {
  const want = [root, real(root)].filter(Boolean);
  let inRoot = false;
  for (const l of (readText(path.join(cx().home, "config.toml")) || "").split(/\r?\n/)) {
    const h = /^\s*\[\s*projects\.(?:"((?:[^"\\]|\\.)*)"|'([^']*)')\s*\]\s*(#.*)?$/.exec(l);
    if (h) { let k = h[2]; if (h[1] !== undefined) { try { k = JSON.parse(`"${h[1]}"`); } catch { k = h[1]; } } inRoot = want.some((w) => samePath(k, w)); continue; }
    if (/^\s*\[/.test(l)) { inRoot = false; continue; }
    if (inRoot && /^\s*trust_level\s*=\s*["']trusted["']/.test(l)) return true;
  }
  return false;
}

// what the installer cannot do: trust and hook approval happen in Codex, by the human
function codexSteps(root, project) {
  const steps = [];
  if (project && !codexTrusted(root)) steps.push("open codex in this repo and trust it: project .codex/ config and hooks load only in a trusted project");
  if (project) steps.push("approve the hivemind hooks in /hooks (Codex asks again only when a hook entry changes)");
  if (!cx().contextModeOn()) steps.push(`add the required context-mode MCP server: ${CODEX_CTX}`);
  if (!steps.length) return;
  log("");
  log("Once, in Codex:");
  steps.forEach((s, i) => log(`  ${i + 1}. ${s}`));
}

const nodeOk = (v = process.versions.node) => {
  const [a, b] = v.split(".").map(Number), [ma, mb] = NODE_MIN.split(".").map(Number);
  return a > ma || (a === ma && b >= mb);
};
const nodeFix = () => (WIN ? "winget install OpenJS.NodeJS.LTS" : "brew install node | sudo pacman -S nodejs npm | nvm install --lts | https://nodejs.org");

// context-mode: installed per ~/.claude/plugins/installed_plugins.json, enabled per settings.json; read only
function contextMode() {
  const inst = readJson(path.join(CLAUDE, "plugins", "installed_plugins.json")) || {};
  const known = readJson(path.join(CLAUDE, "plugins", "known_marketplaces.json")) || {};
  const s = readJson(path.join(CLAUDE, "settings.json")) || {};
  const installed = !!(inst.plugins && Array.isArray(inst.plugins[CTX_PLUGIN]) && inst.plugins[CTX_PLUGIN].length);
  const enabled = !!(s.enabledPlugins && s.enabledPlugins[CTX_PLUGIN] === true);
  return { installed, enabled, known: !!known[CTX_PLUGIN.split("@")[1]] };
}
function contextModeSteps(c = contextMode()) {
  return [
    ...(c.installed || c.known ? [] : [["plugin", "marketplace", "add", CTX_MARKET]]),
    c.installed ? ["plugin", "enable", CTX_PLUGIN, "--scope", "user"] : ["plugin", "install", CTX_PLUGIN, "--scope", "user"],
  ];
}
// through the claude CLI, never by editing settings.json; false (with the commands printed) when it did not take
function installContextMode() {
  const c = contextMode();
  if (c.installed && c.enabled) { log(`plugin   -> ${CTX_PLUGIN} enabled`); return true; }
  const steps = contextModeSteps(c);
  for (const args of steps) {
    const r = spawnSync("claude", args, { stdio: quiet ? "pipe" : "inherit", shell: WIN, timeout: 300000 });
    if (r.status !== 0) break;
  }
  const after = contextMode();
  if (after.installed && after.enabled) { log(`plugin   -> ${CTX_PLUGIN} installed`); return true; }
  warn(`warning: the required context-mode plugin is not ${after.installed ? "enabled" : "installed"}. Run:`);
  for (const args of steps) warn(`  claude ${args.join(" ")}`);
  return false;
}

// project

// Copies of the skill, and unmodified copies of shipped agents, in <dir>/.claude.
// Returns { dupes: [path], overrides: [path] }; act removes the dupes.
function projectDupes(dir, act) {
  const dupes = [], overrides = [];
  if (samePath(real(dir), real(HOME))) return { dupes, overrides }; // ~/.claude is the global install
  for (const s of SKILLS) {
    const p = path.join(dir, codex() ? ".agents" : ".claude", "skills", s);
    const st = lstat(p);
    if (!st) continue;
    if (st.isSymbolicLink()) { dupes.push(p); if (act) removeLink(p); }
    else if (st.isDirectory() && frontmatterName(p) === s && !inside(HERE, p)) { dupes.push(p); if (act) fs.rmSync(p, { recursive: true, force: true }); }
  }
  for (const f of codex() ? [] : shippedAgents()) {
    const p = path.join(dir, ".claude", "agents", f);
    const t = readText(p);
    if (t === null) continue;
    if (norm(t) === norm(fs.readFileSync(path.join(HERE, "agents", f), "utf8")) || pastAgent(f, t)) {
      dupes.push(p);
      if (act) { if (lstat(p).isSymbolicLink()) removeLink(p); else fs.unlinkSync(p); }
    } else overrides.push(p);
  }
  return { dupes, overrides };
}

// an agent file identical to a version this checkout once shipped is an old installer's copy,
// not an edit; needs the checkout's git history, so a non-git copy of hivemind never matches
const pastHashes = {};
function pastAgent(f, text) {
  const hash = (s) => crypto.createHash("sha256").update(norm(s).trimEnd()).digest("hex");
  if (!pastHashes[f]) {
    pastHashes[f] = new Set();
    const commits = git(["log", "--format=%H", "--", `agents/${f}`], HERE);
    for (const c of commits.ok ? commits.out.split("\n").filter(Boolean) : []) {
      const r = spawnSync("git", ["show", `${c}:agents/${f}`], { cwd: HERE, encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] });
      if (r.status === 0) pastHashes[f].add(hash(r.stdout));
    }
  }
  return pastHashes[f].has(hash(text));
}

function registerHooks(root) {
  const script = path.join(HERE, "templates", "hooks", "install-lead-hooks.js");
  const r = spawnSync(process.execPath, [script], { cwd: root, env: { ...process.env, HIVE_HARNESS: HARNESS }, stdio: quiet ? "pipe" : "inherit", encoding: "utf8" });
  if (r.status === 0) return true;
  warn(`error: ${script} exited ${r.status ?? r.error}; lead hooks may be missing`);
  if (quiet && r.stderr) warn(r.stderr.trim());
  return false;
}

function excludeLocal(root, list = EXCLUDE, what = "settings.local.json, hive hooks, hive-owned") {
  const r = git(["rev-parse", "--git-common-dir"], root);
  if (!r.ok) { log("exclude  -> skipped (not a git repo)"); return; }
  const file = path.join(path.resolve(root, r.out), "info", "exclude");
  let text = readText(file) || "";
  const have = text.split(/\r?\n/);
  const add = list.filter((l) => !have.includes(l));
  if (add.length) {
    if (text && !text.endsWith("\n")) text += "\n";
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, text + add.join("\n") + "\n");
  }
  log(`exclude  -> ${path.relative(root, file) || file} (${what})`);
}

// teams/.gitignore is the repo's once copied; a pattern shipped since (a new CLI's skill links)
// is appended. Returns the patterns missing; act writes them.
function teamsIgnore(teams, act) {
  const ign = path.join(teams, ".gitignore"), text = readText(ign);
  const have = (text || "").split(/\r?\n/);
  const add = fs.readFileSync(path.join(HERE, "teams", ".gitignore"), "utf8").split(/\r?\n/).filter((l) => l && !l.startsWith("#") && !have.includes(l));
  if (act && text === null) fs.copyFileSync(path.join(HERE, "teams", ".gitignore"), ign);
  else if (act && add.length) fs.appendFileSync(ign, (text && !text.endsWith("\n") ? "\n" : "") + add.join("\n") + "\n");
  return add;
}

function copyTeams(root) {
  const teams = path.join(root, "teams");
  fs.mkdirSync(teams, { recursive: true });
  teamsIgnore(teams, true);
  for (const f of LINK_SCRIPTS) copyFile(path.join(HERE, "teams", f), path.join(teams, f));
  copyTree(path.join(HERE, "templates"), path.join(teams, "templates"));
  // renamed to worktree-settings.local.json; drop the old copy only if nobody edited it
  const stale = path.join(teams, "templates", "hooks", "settings.local.json");
  const t = readText(stale);
  if (t !== null && !isFile(path.join(HERE, "templates", "hooks", "settings.local.json"))
      && crypto.createHash("sha256").update(norm(t)).digest("hex") === OLD_WORKER_SETTINGS) {
    fs.unlinkSync(stale);
    log("removed  teams/templates/hooks/settings.local.json (renamed to worktree-settings.local.json)");
  }
  // the routing table is the repo's once copied, like PROFILE.md
  if (!lstat(path.join(teams, "ROUTING.md"))) fs.copyFileSync(path.join(HERE, "teams", "ROUTING.md"), path.join(teams, "ROUTING.md"));
  for (const p of L.profiles(path.join(HERE, "teams"))) {
    const src = path.join(HERE, "teams", p), dest = path.join(teams, p);
    fs.mkdirSync(dest, { recursive: true });
    for (const f of ["PROFILE.md", "skills.txt"]) {
      if (isFile(path.join(src, f)) && !lstat(path.join(dest, f))) fs.copyFileSync(path.join(src, f), path.join(dest, f));
    }
    // required.txt is the pipeline's, not the scout's or the repo's: always refreshed
    if (isFile(path.join(src, "required.txt"))) copyFile(path.join(src, "required.txt"), path.join(dest, "required.txt"));
  }
  log(`teams    -> ${teams} (ROUTING.md, PROFILE.md, skills.txt, link-skills.*, templates/)`);
}

function projectInstall(root, opt) {
  const { dupes, overrides } = projectDupes(root, true);
  for (const p of dupes) log(`removed  ${path.relative(root, p)} (duplicate of the global install)`);
  for (const p of overrides) log(`local override kept: ${path.relative(root, p).split(path.sep).join("/")} (differs from shipped; delete it to use the shipped one)`);
  copyTeams(root);
  L.run({ root, install: !!opt.install, confine: !!opt.confine, log });
  // lead autostart + guard: machine-local, never tracked, so worker worktrees do not inherit them
  const ok = registerHooks(root);
  if (codex()) {
    const w = sandboxRoots(root);
    // a config.toml the repo already had may be tracked or the user's: never exclude it
    excludeLocal(root, w.created ? [...CODEX_EXCLUDE, ".codex/config.toml"] : CODEX_EXCLUDE, `hooks.json, hive hooks, rules, hive-owned${w.created ? ", config.toml" : ""}`);
    return ok && !w.error;
  }
  excludeLocal(root);
  return ok;
}

// workspace-write keeps a Codex worker out of ../<repo>-hive/ unless the project names it
function sandboxRoots(root) {
  const w = cx().sandboxRoots(root);
  if (w.error) warn(`warning: ${w.error}`);
  else log(`sandbox  -> ${path.relative(root, w.file)} (${w.changed ? `${w.created ? "created, " : ""}worker worktrees in ${w.dir} writable` : "worktree folder already writable"})`);
  return w;
}

function install(opt) {
  if (!nodeOk()) die(`node ${process.versions.node} is older than ${NODE_MIN}, which the required context-mode plugin needs. Upgrade: ${nodeFix()}, then re-run`);
  const autoUpdate = opt.autoUpdate ? true : opt.noAutoUpdate ? false : undefined;
  const root = process.cwd();
  if (opt.project && samePath(real(root), real(HERE))) die("--project sets up your repo; run it from there, not from the hivemind checkout");
  if (opt.project && samePath(real(root), real(HOME))) die("--project sets up a repo; run it from the repo root, not from your home directory");
  const fresh = !lstat(CONFIG);
  if (codex()) {
    let ok = codexGlobalInstall({ autoUpdate });
    if (opt.project) ok = projectInstall(root, opt) && ok;
    codexSteps(root, opt.project);
    log("");
    log(ok ? "Done. In codex, $hivemind (or /skills) bootstraps the rest." : "Done, with errors above.");
    if (fresh) log("New to hivemind? Ask the hivemind skill for its tour in any repo.");
    return ok;
  }
  let ok = globalInstall({ autoUpdate });
  if (opt.project) ok = projectInstall(root, opt) && ok;
  if (!teamsEnvOn()) {
    log("");
    log("Enable agent teams once, then restart the terminal:");
    log(`  ${envCommand()}`);
  }
  log("");
  log(ok ? "Done. /hivemind bootstraps the rest." : "Done, with errors above.");
  if (fresh) log("New to hivemind? Type /hivemind tour in any repo for a short walkthrough.");
  return ok;
}

// update

// commit subjects a human would care about: features, fixes, anything marked breaking
const CHANGE = /^(feat|fix)(\([^)]*\))?!?:|^\w+(\([^)]*\))?!:/;

function update(argv) {
  const home = real(HERE);
  const top = git(["rev-parse", "--show-toplevel"], home);
  if (!top.ok || !samePath(real(top.out), home)) die(`${home} is not a git checkout; re-clone hivemind to update it`);
  if (git(["status", "--porcelain", "--untracked-files=no"], home).out) {
    die(`${home} has local changes; commit or stash them, then re-run (git -C "${home}" status)`);
  }
  const before = git(["rev-parse", "HEAD"], home).out;
  const pull = git(["pull", "--ff-only"], home);
  if (!pull.ok) die(`git pull --ff-only failed in ${home}:\n${pull.err}\nresolve it by hand (git -C "${home}" status), then re-run`);
  const after = git(["rev-parse", "HEAD"], home).out;
  log(`update   -> ${home} ${before === after ? "already up to date" : `${before.slice(0, 7)}..${after.slice(0, 7)}`}`);
  if (before !== after) {
    const news = git(["log", "--reverse", "--format=%s", `${before}..${after}`], home).out.split("\n").filter((l) => CHANGE.test(l));
    for (const l of news.slice(0, 12)) log(`  ${l}`);
    if (news.length > 12) log(`  … ${news.length - 12} more: git -C "${home}" log ${before.slice(0, 7)}..`);
    // an install from before the tour existed gets a what's-new tour from here, not a first-time one
    const c = readConfig();
    const next = { ...c, ...(c.toured === undefined ? { toured: before } : {}) };
    delete next.behind;
    writeJson(CONFIG, next);
  }
  // the pull may have changed this file: the new code does the install, once per recorded harness
  // unless --harness or HIVE_HARNESS names one
  const rest = argv.filter((a) => a !== "--update");
  const named = harnessArg || process.env.HIVE_HARNESS;
  const had = (readJson(CONFIG) || {}).harnesses;
  const list = named ? [HARNESS] : Array.isArray(had) ? had.filter((h) => HARNESSES.includes(h)) : [];
  if (!list.length) list.push("claude");
  let status = 0;
  for (const h of list) {
    const args = named || h === "claude" ? [...rest] : [...rest, "--harness", h];
    if (!args.includes("--project") && isHiveProject(process.cwd(), h) && !samePath(real(process.cwd()), home)) args.push("--project");
    const r = spawnSync(process.execPath, [path.join(HERE, "install.js"), ...args], { stdio: "inherit" });
    status = status || (r.status ?? 1);
  }
  process.exit(status);
}

// --tour-done: the tour ran or was skipped; the autostart offers it again only after a new feature lands
function tourDone() {
  const head = git(["rev-parse", "HEAD"], real(HERE));
  const next = { ...readConfig(), toured: head.ok && head.out ? head.out : "none" };
  delete next.tourOffers;
  writeJson(CONFIG, next);
  log(`tour     -> done${head.ok ? ` at ${head.out.slice(0, 7)}` : ""}; "tour" in a hivemind session runs it again`);
}

// doctor

async function doctor(fix) {
  const root = process.cwd();
  const top = git(["rev-parse", "--show-toplevel"], root);
  const inRepo = top.ok && !samePath(real(top.out), real(HERE));
  const hive = inRepo && isDir(path.join(root, "teams"));
  const cxh = codex();
  const self = `node "${path.join(HERE, "install.js")}"${cxh ? " --harness codex" : ""}`;
  const hd = cxh ? ".codex" : ".claude";
  const checks = [];
  // test() returns [status, what, fix command]
  const check = (test, fixFn) => checks.push({ test, fixFn });

  check(() => {
    const v = process.versions.node;
    return nodeOk(v) ? ["ok", `node ${v}`] : ["FIX", `node ${v} is older than ${NODE_MIN} (context-mode needs it)`, nodeFix()];
  });
  check(() => has("git") ? ["ok", "git"]
    : ["FIX", "git not found", WIN ? "winget install Git.Git" : "brew install git | sudo pacman -S git | sudo apt install git"]);
  let ghAuthed = false;
  check(() => {
    if (!has("gh")) return ["FIX", "gh not found", WIN ? "winget install GitHub.cli" : "brew install gh | sudo pacman -S github-cli | https://cli.github.com"];
    ghAuthed = has("gh", ["auth", "status"]) !== null;
    return ghAuthed ? ["ok", "gh logged in"] : ["FIX", "gh not logged in", "gh auth login"];
  });
  if (cxh) {
    check(() => cx().contextModeOn() ? ["ok", "context-mode (MCP server or plugin)"]
      : ["WARN", `context-mode (required) is neither an MCP server nor an installed, enabled plugin in ${path.join(cx().home, "config.toml")}`, CODEX_CTX]);
    check(() => {
      const bad = SKILLS.filter((s) => {
        const link = path.join(AGENTS_SKILLS, s);
        return !(lstat(link) && lstat(link).isSymbolicLink() && samePath(real(link), real(path.join(HERE, "skills", s))));
      });
      return bad.length ? ["FIX", `~/.agents/skills/{${bad.join(",")}} not linked to this checkout`, self]
        : ["ok", `~/.agents/skills link to ${path.join(real(HERE), "skills")}`];
    }, () => linkSkills(AGENTS_SKILLS));
    check(() => {
      const { dir, stale } = codexAgentState();
      return stale.length ? ["FIX", `${dir}: ${stale.length} shipped agents missing or stale`, self] : ["ok", "codex agents current"];
    }, () => copyCodexAgents());
    check(() => {
      const { kept } = codexAgentState();
      return kept.length ? ["WARN", `codex agents not generated by hivemind, left alone: ${kept.join(", ")}`, "delete them to use the shipped ones"] : ["ok", "no local agent overrides"];
    });
  }
  if (WIN && !cxh) {
    check(() => has("where", ["bash"]) ? ["ok", "Git Bash"]
      : ["FIX", "bash not found (Claude Code on Windows needs Git Bash)", "winget install Git.Git"]);
  }
  if (!cxh) {
    check(() => teamsEnvOn() ? ["ok", `${TEAMS_ENV}=1`]
      : ["FIX", `${TEAMS_ENV} not set`, `${envCommand()}, then restart the terminal`]);
    check(() => {
      const cache = path.join(CLAUDE, "plugins", "cache");
      const found = (isDir(cache) ? fs.readdirSync(cache) : []).some((m) => {
        const d = path.join(cache, m, "mattpocock-skills");
        return isDir(d) && fs.readdirSync(d).some((v) => isDir(path.join(d, v, "skills")));
      });
      return found ? ["ok", "mattpocock-skills plugin"]
        : ["FIX", "mattpocock-skills plugin missing", "inside Claude Code: /plugin install mattpocock-skills@claude-plugins-official"];
    });
    check(() => {
      const c = contextMode();
      return c.installed && c.enabled ? ["ok", `${CTX_PLUGIN} plugin`]
        : ["FIX", `${CTX_PLUGIN} plugin (required) ${c.installed ? "disabled" : "missing"}`, contextModeSteps(c).map((a) => `claude ${a.join(" ")}`).join(" && ")];
    }, () => installContextMode());
    check(() => {
      const bad = SKILLS.filter((s) => {
        const link = path.join(CLAUDE, "skills", s);
        return !(lstat(link) && lstat(link).isSymbolicLink() && samePath(real(link), real(path.join(HERE, "skills", s))));
      });
      return bad.length ? ["FIX", `~/.claude/skills/{${bad.join(",")}} not linked to this checkout`, self]
        : ["ok", `global skills link to ${path.join(real(HERE), "skills")}`];
    }, () => linkSkills());
    check(() => {
      const stale = shippedAgents().filter((f) => {
        const t = readText(path.join(CLAUDE, "agents", f));
        return t === null || norm(t) !== norm(fs.readFileSync(path.join(HERE, "agents", f), "utf8"));
      });
      return stale.length ? ["FIX", `~/.claude/agents: ${stale.length} shipped agents missing or stale`, self] : ["ok", "global agents current"];
    }, () => copyAgents());
  }
  check(() => {
    const c = readJson(path.join(CLAUDE, "hivemind.json"));
    return c && samePath(c.home, real(HERE)) ? ["ok", `hivemind.json home, autoUpdate ${c.autoUpdate === true}`]
      : ["FIX", "~/.claude/hivemind.json missing or points elsewhere", self];
  }, () => writeConfig());
  if (!cxh) check(() => {
    const s = readJson(path.join(CLAUDE, "settings.json"));
    const a = s && s.attribution;
    if (!s) return ["FIX", "~/.claude/settings.json is not valid JSON", "fix it by hand, then re-run"];
    return a && a.commit === "" && a.pr === "" ? ["ok", "attribution off"] : ["FIX", "attribution not disabled", self];
  }, () => setAttribution());

  // skill copies in this dir or a parent (below $HOME) show /hivemind twice
  const dirs = [];
  for (let d = root; ; d = path.dirname(d)) {
    if (samePath(real(d), real(HOME))) break;
    dirs.push(d);
    if (path.dirname(d) === d) break;
  }
  check(() => {
    const dupes = dirs.flatMap((d) => projectDupes(d, false).dupes);
    return dupes.length ? ["FIX", `duplicate copies: ${dupes.join(", ")}`, `${self} --doctor --fix`] : ["ok", "no duplicate skill or agent copies"];
  }, () => dirs.forEach((d) => projectDupes(d, true)));
  if (!cxh) check(() => {
    const kept = dirs.flatMap((d) => projectDupes(d, false).overrides);
    return kept.length ? ["WARN", `local agent overrides: ${kept.join(", ")}`, "delete them to use the shipped ones"] : ["ok", "no local agent overrides"];
  });

  if (!inRepo) {
    const where = top.ok ? "in the hivemind checkout" : "not inside a git repo";
    check(() => ["WARN", `${where}; project checks skipped`, "cd into your repo and re-run"]);
  } else {
    check(() => {
      const remotes = git(["remote", "-v"], root).out;
      if (!/github\.com/.test(remotes)) return ["FIX", "no GitHub remote", "gh repo create --private --source . --push"];
      if (!ghAuthed) return ["WARN", "GitHub remote not verified (gh not ready)", "gh auth login"];
      const r = spawnSync("gh", ["repo", "view", "--json", "nameWithOwner", "-q", ".nameWithOwner"], { cwd: root, encoding: "utf8", shell: WIN, timeout: 20000 });
      return r.status === 0 ? ["ok", `GitHub repo ${r.stdout.trim()}`] : ["FIX", "gh repo view fails for this repo's remote", "git remote -v; gh repo view"];
    });
    if (!hive) {
      check(() => ["WARN", "not a hivemind project (no teams/)", `${self} --project`]);
    } else {
      check(() => isFile(path.join(root, "teams", "ROUTING.md")) ? ["ok", "teams/ROUTING.md"]
        : ["WARN", "teams/ROUTING.md missing", `${self} --project`]);
      check(() => {
        const s = readJson(path.join(root, ...(cxh ? [".codex", "hooks.json"] : [".claude", "settings.local.json"])));
        const hooks = JSON.stringify((s && s.hooks) || {});
        const miss = ["hive-autostart.js", "hive-lead-guard.js"].filter((f) => !hooks.includes(f) || !isFile(path.join(root, hd, "hooks", f)));
        return miss.length ? ["FIX", `lead hooks not registered: ${miss.join(", ")}`, `${self} --project`] : ["ok", "lead hooks registered"];
      }, () => registerHooks(root));
      if (cxh) {
        check(() => {
          const left = cx().skipHooks.filter((f) => lstat(path.join(root, hd, "hooks", f)));
          return left.length ? ["FIX", `Claude-only files in .codex/hooks: ${left.join(", ")}`, `${self} --project`] : ["ok", "no Claude-only files in .codex/hooks"];
        }, () => registerHooks(root));
        check(() => readText(path.join(root, ".codex", "rules", "hivemind.rules")) === cx().RULES ? ["ok", ".codex/rules/hivemind.rules"]
          : ["FIX", ".codex/rules/hivemind.rules missing or stale", `${self} --project`], () => registerHooks(root));
        check(() => {
          const w = cx().sandboxRoots(root, false);
          if (w.error) return ["FIX", w.error.replace(/; add .*/, ""), `add ${w.dir} to writable_roots under [sandbox_workspace_write] in .codex/config.toml`];
          return w.missing ? ["FIX", `workers cannot write in ${w.dir}: .codex/config.toml does not list it in writable_roots`, `${self} --project`]
            : ["ok", "worktree folder writable in the Codex sandbox"];
        }, () => { if (sandboxRoots(root).created) excludeLocal(root, [".codex/config.toml"], "config.toml"); });
        check(() => codexTrusted(root) ? ["ok", "project trusted in codex"]
          : ["WARN", "project not trusted in codex: its .codex/ hooks do not load", "open codex here, trust the project, approve the hooks in /hooks"]);
      }
      check(() => {
        const r = spawnSync(process.execPath, [path.join(HERE, "templates", "hooks", "hive-scratch.js"), "--size"], { cwd: root, encoding: "utf8", timeout: 60000 });
        const mb = parseFloat(r.stdout);
        if (r.status !== 0 || !Number.isFinite(mb)) return ["WARN", "scratch size unknown", `node ${hd}/hooks/hive-scratch.js --size`];
        return mb > 1024 ? ["WARN", `hive scratch holds ${mb} MB`, `node ${hd}/hooks/hive-scratch.js --sweep --all-done`] : ["ok", `hive scratch ${mb} MB`];
      });
      check(() => {
        const teams = path.join(root, "teams");
        const dir = (p) => (cxh ? cx().teamSkills(path.join(teams, p)) : path.join(teams, p, ".claude", "skills"));
        const unlinked = L.profiles(teams).map((p) => [p, L.listFiles(path.join(teams, p)).flatMap(L.readList)
          .filter(([, name]) => name && !real(path.join(dir(p), name))).length]).filter(([, n]) => n);
        const ign = teamsIgnore(teams, false);
        if (ign.length) return ["FIX", `teams/.gitignore lacks ${ign.join(", ")} (skill links would be committed)`, `${self} --project`];
        return unlinked.length ? ["FIX", `team skills not linked (${unlinked.map(([p, n]) => `${p} ${n}`).join(", ")})`, `node "${path.join(HERE, "teams", "link-skills.js")}" --install`]
          : ["ok", "team skills linked"];
      }, () => { teamsIgnore(path.join(root, "teams"), true); L.run({ root, log }); });
      // CI runs the gate on a clean checkout: the file it names must be tracked (a Codex-only repo
      // has no .claude/hooks/commit-msg.js, and .codex/hooks is machine-local)
      check(() => {
        const found = [], bad = [];
        for (const f of ["lefthook.yml", ".github/workflows/hive-gates.yml"]) {
          for (const m of (readText(path.join(root, f)) || "").matchAll(/\bnode\s+["']?([^\s"']*commit-msg\.js)/g)) {
            found.push(f);
            if (!git(["ls-files", "--error-unmatch", "--", m[1]], root).ok) bad.push(`${f} runs ${m[1]}`);
          }
        }
        if (bad.length) return ["FIX", `commit-msg gate: ${bad.join("; ")}, which git does not track`, `point it at ${COMMIT_MSG} and commit`];
        return ["ok", found.length ? "commit-msg gate runs a tracked file" : "commit-msg gate not installed yet (the scaffold ticket adds it)"];
      });
    }
  }

  let failing = 0;
  for (const c of checks) {
    let r = await c.test();
    if (r[0] === "FIX" && fix && c.fixFn) {
      quiet = true;
      try { c.fixFn(); } catch (e) { warn(`fix failed: ${e.message}`); } finally { quiet = false; }
      r = await c.test();
      if (r[0] !== "FIX") r[1] += " (fixed)";
    }
    if (r[0] === "FIX") failing++;
    console.log(`${r[0].padEnd(4)} ${r[1]}${r[0] === "ok" ? "" : ` — ${r[2]}`}`);
  }
  console.log(failing ? `\n${failing} to fix${fix ? "" : "; --doctor --fix applies the local ones"}` : "\nall good");
  return failing === 0;
}

// main

const FLAGS = {
  "--project": "project", "--install": "install", "--confine": "confine", "--update": "update",
  "--doctor": "doctor", "--fix": "fix", "--auto-update": "autoUpdate", "--no-auto-update": "noAutoUpdate",
  "--tour-done": "tourDone",
};
const argv = process.argv.slice(2);
const opt = {};
let harnessArg = null;
for (let i = 0; i < argv.length; i++) {
  const a = argv[i];
  if (a === "--harness" || a.startsWith("--harness=")) {
    harnessArg = a === "--harness" ? argv[++i] : a.slice("--harness=".length);
    if (!harnessArg) die(`--harness needs a value: ${HARNESSES.join(" or ")}`, 2);
    continue;
  }
  if (a === "-h" || a === "--help") {
    const lines = fs.readFileSync(__filename, "utf8").split(/\r?\n/).slice(1);
    console.log(lines.slice(0, lines.findIndex((l) => !l.startsWith("//"))).map((l) => l.slice(3)).join("\n"));
    process.exit(0);
  }
  if (!FLAGS[a]) die(`unknown flag: ${a} (--help lists them)`, 2);
  opt[FLAGS[a]] = true;
}
HARNESS = String(harnessArg || process.env.HIVE_HARNESS || "claude").toLowerCase();
if (!HARNESSES.includes(HARNESS)) die(`unknown harness: ${HARNESS} (${HARNESSES.join(" or ")})`, 2);
if ((opt.install || opt.confine) && !opt.project) die("--install/--confine need --project", 2);
if (opt.confine && codex()) die("--confine hides skills from Claude Code only; Codex reads ~/.agents/skills itself", 2);
if (opt.fix && !opt.doctor) die("--fix needs --doctor", 2);
if (opt.doctor && Object.keys(opt).some((k) => k !== "doctor" && k !== "fix")) die("--doctor takes only --fix", 2);
if (opt.tourDone && Object.keys(opt).length > 1) die("--tour-done takes no other flag", 2);
if (opt.autoUpdate && opt.noAutoUpdate) die("--auto-update and --no-auto-update conflict", 2);

(async () => {
  if (opt.doctor) process.exitCode = (await doctor(opt.fix)) ? 0 : 1;
  else if (opt.tourDone) tourDone();
  else if (opt.update) update(argv);
  else process.exitCode = install(opt) ? 0 : 1;
})().catch((e) => die(`error: ${e.message}`));
